apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 563186623770.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newName: 563186623770.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newTag: abcdefg
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
